[package]
name = "Rust-wasm"
version = "0.1.0"
description = "A sample project with wasm-pack"

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-Oz", "--enable-mutable-globals"]

[lib]
crate-type = ["cdylib"]
path = "./src/lib.rs"

[dependencies]
wasm-bindgen = "0.2.64"
rand = "0.7.0"
