[package]
name = "Rust-wasm"
version = "0.1.0"
description = "A sample project with wasm-pack"
license = "MIT/Apache-2.0"
edition = '2018'
repository = "https://github.com/akeboshi1/PhaserRust"
[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-Oz", "--enable-mutable-globals"]

[lib]
crate-type = ["cdylib"]
path = "./src/lib.rs"

[dependencies]
wasm-bindgen = "0.2.64"
wasm-bindgen-futures = "0.4.7"
rand = "0.7.0"
